#!/usr/bin/env python3

import skilstak.colors as col
from os import system as sys
import time as t
import math

def main():
    print(col.clear + '''You can do:
            1 - Addition
            2 - Subtraction
            3 - Multiplication
            4 - Division
            5 - Quadratics
            6 - Trigonometry''')
    qwe = input("What do you want to do? >> ").strip()
    if qwe == '1':
        print("You chose addition")
        first = input("What is your first number? >> ")
        second = input("What is your second number? >> ")
        answer = int(first) + int(second)
        print("Your answer is " + str(answer))
    elif qwe == '2':
        print("You chose subtraction")
        first = input("What is your first number? >> ")
        second = input("What is your second number? >> ")
        answer = int(first) - int(second)
        print("Your answer is " + str(answer))
    elif qwe == '3':
        print("You chose multiplication")
        first = input("What is your first number? >> ")
        second = input("What is your second number? >> ")
        answer = int(first) * int(second)
        print("Your answer is " + str(answer))
    elif qwe == '4':
        print("You chose division")
        first = input("What is your first number? >> ")
        second = input("What is your second number? >> ")
        answer = int(first)/int(second)
        print("Your answer is " + str(answer))
    elif qwe == '5':
        print("You chose quadratics")
        a = input("What is your A value? >> ")
        b = input("What is your B value? >> ")
        c = input("What is your C value? >> ")
        aos = 0 - int(b)/(2*int(a))
        this = float(a)*float(aos)*float(aos)
        that = float(b)*float(aos)
        thus = float(c)
        xvertex = this + that + thus
        print("The y intercept is " + str(c))
        print("The axis of symmetry is " + str(aos))
        print("The vertex is (" + str(aos) + "," + str(xvertex) + ")")
        if int(b) > 4*int(a)*int(c):
            begin = -1*float(b)
            middle = float(b)*float(b)
            end = 4*float(a)*float(c)
            squareroot = middle - end
            final = 2*float(a)
            root1 = (begin + math.sqrt(squareroot))/final
            root2 = (begin - math.sqrt(squareroot))/final
            message = "The roots are at " + str(root1) + " and " + str(root2)
        elif float(b)-(4*float(a)*float(c))<0:
            message = "There are no real roots"
        else:
            root = (-1*int(b) + math.sqrt(int(b)^2 - 4*int(a)*int(c)))/2*int(a)
            message = "There is only one root and it is at " + str(root)
        print(message)
    elif qwe == '6':
        print("You chose trigonometry")
        reference = input("What is the degree of your reference angle? >> ")
        whichside = input("Do you already have the measure of the adjacent side(1), the opposite side(2), or the hypotenuse(3)? >> ")
        length = input("What is the length of the side you have? >> ")
        if whichside == '1':
            print("You have the adjacent side")
            input("YOU WILL GET A WRONG ANSWER RIGHT NOW")
            opp = math.tan(math.degrees(int(reference)))*int(length)
            print("The opposite side is " + str(opp))
            hyp = math.tan(math.degrees(90 - int(reference)))*int(length)
            print("The hypotenuse is " + str(hyp))
        else:
            pass
    else:
        print("INVALID INPUT")
        t.sleep(2)
        main()
    
if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        exit()
