#!/usr/bin/env python3
Author="Cole Vahey"

import skilstak.colors as col
from os import system as sys
import time as t
import math

def main():
    print(col.clear + '''You can do:
            1 - Addition
            2 - Subtraction
            3 - Multiplication
            4 - Division
            5 - Pythagorean Theorum
            6 - Quadratic Equation''')
    qwe = input("What do you want to do? >> ").strip()
    if qwe == '1':
        addition()
    elif qwe == '2':
        subtraction()
    elif qwe == '3':
        multiplication()
    elif qwe == '4':
        division()
    elif qwe == '5':
        pythagorean()
    elif qwe == '6':
        quadratics()
    else:
        print("INVALID INPUT")
        input("Press enter to try again")
        main()
    
def addition():
    print("You chose addition")
    first = input("What is your first number? >> ")
    second = input("What is your second number? >> ")
    answer = int(first) + int(second)
    print("Your answer is " + str(answer))

def subtraction():
    print("You chose subtraction")
    first = input("What is your first number? >> ")
    second = input("What is your second number? >> ")
    answer = int(first) - int(second)
    print("Your answer is " + str(answer))

def multiplication():
    print("You chose multiplication")
    first = input("What is your first number? >> ")
    second = input("What is your second number? >> ")
    answer = int(first) * int(second)
    print("Your answer is " + str(answer))

def division():
    print("You chose division")
    first = input("What is your first number? >> ")
    second = input("What is your second number? >> ")
    answer = int(first)/int(second)
    print("Your answer is " + str(answer))

def pythagorean():
    print("You chose pythagorean theorum")
    hyp = input("Do you have your hypotenuse[Y/N]? >> ")
    if hyp.title() == 'Y':
        a = input("What is the hypotenuse? >> ")
        b = input("What is the other side? >> ")
        if int(a) < int(b):
            print("That is impossible")
            input("[Press enter to continue]")
            pythagorean()
        else:
            final = (float(a)*float(a))-(float(b)*float(b))
            finalside = math.sqrt(final)
    elif hyp.title() == 'N':
        a = input("What is your first side? >> ")
        b = input("What is your second side? >> ")
        final = (float(a)*float(a))+(float(b)*float(b))
        finalside = math.sqrt(final)
    else:
        pythagorean()
    print("Your final side is " + str(finalside))

def quadratics():
    print("You chose quadratics")
    a = input("What is your A value? >> ")
    b = input("What is your B value? >> ")
    c = input("What is your C value? >> ")
    aos = 0 - int(b)/(2*int(a))
    this = float(a)*float(aos)*float(aos)
    that = float(b)*float(aos)
    thus = float(c)
    xvertex = this + that + thus
    begin = -1*float(b)
    middle = float(b)*float(b)
    end = 4*float(a)*float(c)
    squareroot = middle - end
    final = 2*float(a)
    print("The y intercept is " + str(c))
    print("The axis of symmetry is " + str(aos))
    print("The vertex is (" + str(aos) + "," + str(xvertex) + ")")
    if int(b) > 4*int(a)*int(c):
        root1 = (begin + math.sqrt(squareroot))/final
        root2 = (begin - math.sqrt(squareroot))/final
        message = "The roots are at " + str(root1) + " and " + str(root2)
    elif squareroot < 0:
        message = "There are no real roots"
    else:
        root = begin/final
        message = "There is only one root and it is at " + str(root)
    print(message)

if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        exit()
